{"name": "Prueba de login fallido", "status": "passed", "description": "Verifica que el login falle con credenciales incorrectas", "attachments": [{"name": "stdout", "source": "0d18ee9e-3580-4086-a73e-4d3a5d617c37-attachment.txt", "type": "text/plain"}], "start": 1747668959596, "stop": 1747668959722, "uuid": "f0ab5b3e-d8d0-4a88-ad1a-cb471af01c51", "historyId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "testCaseId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "fullName": "EcoGuardian.tests.test_eco_guardian.AuthTests#test_login_fallido", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "EcoGuardian.tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "AuthTests"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "2856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "EcoGuardian.tests.test_eco_guardian"}]}