{"name": "Prueba de login fallido", "status": "passed", "description": "Verifica que el login falle con credenciales incorrectas", "attachments": [{"name": "stdout", "source": "71b1382a-4362-4b52-bb34-7920ee8ae2ca-attachment.txt", "type": "text/plain"}], "start": 1746894649938, "stop": 1746894650178, "uuid": "6319a497-1c20-4620-ab02-bade86a87c81", "historyId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "testCaseId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "fullName": "EcoGuardian.tests.test_eco_guardian.AuthTests#test_login_fallido", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "EcoGuardian.tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "AuthTests"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "9568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "EcoGuardian.tests.test_eco_guardian"}]}