{"name": "Prueba de login fallido", "status": "passed", "description": "Verifica que el login falle con credenciales incorrectas", "attachments": [{"name": "stdout", "source": "cf535a1f-6ce4-4cb0-b2fc-81b929ed739b-attachment.txt", "type": "text/plain"}], "start": 1747669503354, "stop": 1747669503447, "uuid": "7e120093-e4cb-4562-a322-76f1a5d84d1e", "historyId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "testCaseId": "f892cd1ad0909e3cab6ddca4d9ed5d9b", "fullName": "EcoGuardian.tests.test_eco_guardian.AuthTests#test_login_fallido", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "EcoGuardian.tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "AuthTests"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "16252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "EcoGuardian.tests.test_eco_guardian"}]}